export const BE_PARTNER_DATA = 'BE_PARTNER_DATA';
export const ORDER_RESEARCH_DATA = 'ORDER_RESEARCH_DATA';
export const REGISTRATION_CLIENT = 'REGISTRATION_CLIENT';
export const REGISTRATION_CLIENT_ERROR = 'REGISTRATION_CLIENT_ERROR';